Only show light and barrier when holding the item
ModGardenEvent/barricade pull request #2
Opened 2024-11-16 20:09 UTC by Tomate0613

Fixes #1

2024-11-16 21:25 UTC, sylv256 requested changes

2024-11-16 21:25 UTC, sylv256 commented on common/src/main/java/net/modgarden/barricade/mixin/client/BarrierBlockMixin.java
> +        if (player == null || !player.canUseGameMasterBlocks() || !player.getMainHandItem().is(Items.BARRIER)) {
```java
!player.getMainHandItem().is(Items.BARRIER)
```
This doesn't work for custom barriers that Barricade adds. Consider adding an item tag.

2024-11-16 21:27 UTC, Tomate0613 commented on common/src/main/java/net/modgarden/barricade/mixin/client/BarrierBlockMixin.java
> +        if (player == null || !player.canUseGameMasterBlocks() || !player.getMainHandItem().is(Items.BARRIER)) {
Pug is already working on a propper fix, so this isn't really needed anyways

2024-11-17 02:22 UTC, closed without merging

2024-11-17 02:23 UTC, MerchantPug commented
To give an official response, this PR was a bandaid fix.
I have now fixed the incompatibility with Sodium in 1.1.0.